SmartTrash/config/routes.rb
Rails.application.routes.draw do
  resources :userdevices
  resources :alarmlogs
  resources :schedulers
  get 'dmaps/layout' =>"dmaps#layout"
  resources :dmaps
  resources :contacts
  resources :sensors
  get 'alarms/toAddAlarms' =>"alarms#toAddAlarms"
  get 'alarms/toUpdateAlarms' =>"alarms#toUpdateAlarms"
  post 'alarms/querySensorByDeviceId' =>"alarms#querySensorByDeviceId"
  post 'alarms/addAlarms' =>"alarms#addAlarms"
  post 'queryAlarmlogs' =>"alarmlogs#queryAlarmlogs"
  post 'alarms/:id/update' =>"alarms#update"
  get 'devices/monitor' =>"devices#monitor"
  get 'devices/layout' =>"devices#layout"
  get 'devices/explore' =>"devices#explore"
  get 'devices/queryLineData' =>"devices#queryLineData"
  post 'devices/:id/update' =>"devices#update"
  post 'devices/getDevices' =>"devices#getDevices"
  post 'history' =>"devices#history"
  get 'history' =>"devices#history"
  post 'goHistoryLine' =>"devices#goHistoryLine"
  get 'goHistoryLine' =>"devices#goHistoryLine"
  get 'sensorlogs/getData' =>"sensorlogs#getData"
  post 'sensorlogs/getData' =>"sensorlogs#getData"
  post 'querySensorHistoryDatas' =>"sensorlogs#querySensorHistoryDatas"
  post 'querySensorDataDetail' =>"sensors#querySensorDataDetail"
  get 'getSensorsByID' =>"sensors#getSensorsByID"
  resources :devices
  resources :projects
  resources :sensorlogs
  get 'home/index'
  root to: "users#login"
  get 'login' => 'users#login'
  get 'register' => 'users#register'
  post 'register' => 'users#register'
  post 'login' => 'users#create_login_session'
  delete 'logout' => 'users#logout'
  get 'logout' => 'users#logout'
  get '/users/toUpdatePassword' => 'users#toUpdatePassword'
  post '/users/toUpdatePassword' => 'users#toUpdatePassword'
  get 'devicebinding' => 'users#devicebinding'
  post 'users/binding' => 'users#binding'
  post 'users/delbinding' => 'users#delbinding'
  resources :alarms
  resources :users
  resources :gateways
  resources :devices
  resources :projects

end

SmartTrash/app/models/userdevice.rb
class Userdevice
  include MongoMapper::Document

  key :user_id, String
  key :device_id, String

end

SmartTrash/app/controllers/userdevices_controller.rb
class UserdevicesController < ApplicationController
  before_action :set_userdevice, only: [:show, :edit, :update, :destroy]

  # GET /userdevices
  # GET /userdevices.json
  def index
    @userdevices = Userdevice.all
  end

  # GET /userdevices/1
  # GET /userdevices/1.json
  def show
  end

  # GET /userdevices/new
  def new
    @userdevice = Userdevice.new
  end

  # GET /userdevices/1/edit
  def edit
  end

  # POST /userdevices
  # POST /userdevices.json
  def create
    @userdevice = Userdevice.new(userdevice_params)

    respond_to do |format|
      if @userdevice.save
        format.html { redirect_to @userdevice, notice: 'Userdevice was successfully created.' }
        format.json { render :show, status: :created, location: @userdevice }
      else
        format.html { render :new }
        format.json { render json: @userdevice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /userdevices/1
  # PATCH/PUT /userdevices/1.json
  def update
    respond_to do |format|
      if @userdevice.update(userdevice_params)
        format.html { redirect_to @userdevice, notice: 'Userdevice was successfully updated.' }
        format.json { render :show, status: :ok, location: @userdevice }
      else
        format.html { render :edit }
        format.json { render json: @userdevice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /userdevices/1
  # DELETE /userdevices/1.json
  def destroy
    @userdevice.destroy
    respond_to do |format|
      format.html { redirect_to userdevices_url, notice: 'Userdevice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_userdevice
      @userdevice = Userdevice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def userdevice_params
      params.require(:userdevice).permit(:user_id, :device_id)
    end
end

SmartTrash/app/helpers/userdevices_helper.rb
module UserdevicesHelper
end

SmartTrash/app/views/userdevices/_form.html.erb
<%= form_for(@userdevice) do |f| %>
  <% if @userdevice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@userdevice.errors.count, "error") %> prohibited this userdevice from being saved:</h2>

      <ul>
      <% @userdevice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :device_id %><br>
    <%= f.text_field :device_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

SmartTrash/app/views/userdevices/edit.html.erb
<h1>Editing Userdevice</h1>

<%= render 'form' %>

<%= link_to 'Show', @userdevice %> |
<%= link_to 'Back', userdevices_path %>

SmartTrash/app/views/userdevices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Userdevices</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Device</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @userdevices.each do |userdevice| %>
      <tr>
        <td><%= userdevice.user_id %></td>
        <td><%= userdevice.device_id %></td>
        <td><%= link_to 'Show', userdevice %></td>
        <td><%= link_to 'Edit', edit_userdevice_path(userdevice) %></td>
        <td><%= link_to 'Destroy', userdevice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Userdevice', new_userdevice_path %>

SmartTrash/app/views/userdevices/new.html.erb
<h1>New Userdevice</h1>

<%= render 'form' %>

<%= link_to 'Back', userdevices_path %>

SmartTrash/app/views/userdevices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @userdevice.user_id %>
</p>

<p>
  <strong>Device:</strong>
  <%= @userdevice.device_id %>
</p>

<%= link_to 'Edit', edit_userdevice_path(@userdevice) %> |
<%= link_to 'Back', userdevices_path %>